export interface RoleProps {
  id: number;
  nombre: string;
  descripcion?: string;
  permisos: string[];
}

export class Role {
  private constructor(private props: RoleProps) {}

  static create(props: Omit<RoleProps, 'id'>): Role {
    return new Role({
      ...props,
      id: Date.now(), // Should be generated by repository
    });
  }

  static restore(props: RoleProps): Role {
    return new Role(props);
  }

  getId(): number {
    return this.props.id;
  }

  getNombre(): string {
    return this.props.nombre;
  }

  getDescripcion(): string | undefined {
    return this.props.descripcion;
  }

  getPermisos(): string[] {
    return this.props.permisos;
  }

  hasPermission(permission: string): boolean {
    return this.props.permisos.includes(permission);
  }

  updateNombre(nombre: string): void {
    if (!nombre || nombre.trim().length === 0) {
      throw new Error('Role name is required');
    }
    this.props.nombre = nombre.trim();
  }

  updateDescripcion(descripcion: string): void {
    this.props.descripcion = descripcion.trim();
  }

  updatePermisos(permisos: string[]): void {
    this.props.permisos = permisos;
  }

  toObject(): RoleProps {
    return { ...this.props };
  }
}